#  一、Promise

<https://mp.weixin.qq.com/s/UynkFFsmY1c7f_pAdDHJ3A>，前端自习课，【总结】2277- 为什么 try catch 能捕捉 await 后 Promise 的错误？